### PR TITLE
Remove unused val

### PR DESCRIPTION
**Pull request by alissapajer**

### CODE REVIEW

**Comment by alissapajer** [comment]
🛑 is up because we're in the last stages of QA for a release, and I want to leave the trickle flow open for anything more urgent.

**Review by cryogenian — CHANGES_REQUESTED** [review]
This is incorrect, the identifier isn't used indeed, but `buffer.get` is used. Mutating state.

**Comment by alissapajer** [comment]
What state is being mutated?

The [javadoc for `ByteBuffer#get`](https://docs.oracle.com/javase/8/docs/api/java/nio/ByteBuffer.html#get-int-) doesn't indicate that any state is being mutated.

**Comment by rintcius** [comment]
@alissapajer It's this one https://docs.oracle.com/javase/7/docs/api/java/nio/ByteBuffer.html#get(byte[],%20int,%20int) and copies bytes into the `tgt` array

**Comment by alissapajer** [comment]
Added a comment and removed the let binding.

**Review by cryogenian — APPROVED** [review]

**Review by dcsobral — APPROVED** [review]

**Pull request merged**
