### PR TITLE
Add logging middleware

### PR DESCRIPTION
**Pull request by dcsobral**

### CODE REVIEW

**Comment by dcsobral** [comment]
Please review commit c26f6d7 in particular.

**Comment by alissapajer** [comment]
Could you move to everything that's in `impl.datasources.middleware` to  `impl.logging`, per @wemrysi 's comment on https://github.com/precog/quasar/pull/4707

**Comment by dcsobral** [comment]
Sure, I'll move it. I checked for comments before closing that PR and didn't see it. :/

**Review by alissapajer — APPROVED** [review]
Good to merge, once the package change is made.

**Pull request merged**
