### PR TITLE
Added default integer param

### PR DESCRIPTION
**Pull request by beckyconning**

### CODE REVIEW

**Comment by cryogenian** [comment]
The build failed, some `Args` stuff in test

**Comment by beckyconning** [comment]
Will add = None once things are working well

**Comment by beckyconning** [comment]
Fixing tests now

**Comment by djspiewak** [comment]
FYI you can also trigger the build by pressing the "re-run build" button. :-)

**Comment by beckyconning** [comment]
We tried that but it didn't fix it.

**Comment by beckyconning** [comment]
Looks like the commit maxim made is building fine, weird. I'll try making another commit once this one has built.

**Comment by djspiewak** [comment]
I can confirm it builds locally without a problem, both on Graal and OpenJDK. I have no explanation.

**Comment by beckyconning** [comment]
👻 It is a mystery 👻

**Comment by wemrysi** [comment]
NB, this should have been marked as `breaking` as all the destinations that define types without using named args (currently all of them) break. Even if it was bin/source compat `feature` would still be more appropriate.

**Pull request merged**
